name: AfkFishing
main: me.aov.AfkFishing
api-version: 1.17
version: 1.0
softdepend:
    - HolographicDisplays
    - GSit
commands:
    fish:
        description: "Test"
        usage: "/fish"
        permission: "joe"