name: AfkFishing
main: me.aov.AfkFishing
api-version: 1.17
version: 1.0
softdepend:
    - HolographicDisplays
commands:
    fish:
        description: "Commands for AfkFishing"
        usage: "/fish"
        permission: "afkfishing.command"